import { Schema, model, models } from "mongoose";

// Define the structure of a user document in MongoDB
const UserSchema = new Schema({
  // Unique identifier generated by Clerk
  clerkId: { type: String, required: true, unique: true },
  // Unique email address of the user
  email: { type: String, required: true, unique: true },
  // Unique username chosen by the user
  username: { type: String, required: true, unique: true },
  // URL of the user's profile picture
  photo: { type: String, required: true },
  // First name of the user
  firstName: { type: String },
  // Last name of the user
  lastName: { type: String },
});

// Create or retrieve the User model from MongoDB
const User = models?.User || model("User", UserSchema);

// Export the User model for use in other parts of the application
export default User;
